version: "3.8"
services: 
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mynetwork
  frontend: 
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - mynetwork
networks:
  mynetwork:
