version: "3.8"
services:
  bookwormbackend:
    build: ./backend
    image: bookworm/redis:6.0.8
    container_name: backendcontainer
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - bookwormnetwork

  bookwormfrontend:
    build: ./frontend
    image: bookworm/frontend:v1
    container_name: frontendcontainer
    environment:
      REDIS: bookworm-backend
    ports:
      - 80
    stdin_open: true
    tty: true
    command: npm run build
    networks:
      - bookwormnetwork

networks:
  bookwormnetwork:
    driver: bridge

    
