version: "3.8"
services:
  bookwormbackend:
    build: ./backend
    image: bookwormarc.azurecr.io/oss/bitnami/redis:6.0.8
    container_name: backendcontainer
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - bookwormnetwork

  bookwormfrontend:
    build: ./frontend
    image: bookwormarc.azurecr.io/azuredocs/frontend:v1
    container_name: frontendcontainer
    environment:
      REDIS: bookworm-backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - bookwormbackend
    networks:
      - bookwormnetwork

  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bookwormnetwork

networks:
  bookwormnetwork:
    driver: bridge

    